Creating profile slf4j-log4j12 which is activated by default, I need to disble it when running with EAP dependencies, org.opensaml:openws has dependencies on org.slf4j:log4j-over-slf4j and it colides with slf4j-log4j12 dependency in project -- org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException ... Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.test.ws.jaxws.bp12...TestCase